[tool.isort]
profile = "black"
skip_gitignore = true

[flake8]
max-line-length = 88
extend-ignore = "E203"

[tool.ruff]
exclude = ["algo_trading/migrations", "algo_trading/models/__init__.py", "algo_trading/static/*", "static/*"]


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "algo_trading.settings.development"
